### PR TITLE
Create workspace directory

### PR DESCRIPTION
**Pull request by OliverWoolland**
A set of changes to introduce a workspace directory in this style:

Untitled presentation

### CODE REVIEW

**Comment by OliverWoolland** [comment]
I struggled a bit with the README changes but think it is correct now! They should definitely be double checked

**Review by OliverWoolland — COMMENTED** [review]
Quick look over seems ok to me

**Comment by fritjof-b** [comment]
We changed `documentation` -> `docs` because of GitHub naming conventions. Could you rename on your branch as well?

**Comment by OliverWoolland** [comment]
> We changed `documentation` -> `docs` because of GitHub naming conventions. Could you rename on your branch as well?

done hopefully!

**Comment by OliverWoolland** [comment]
Finally! Slightly whack-a-mole but looks like everything is passing now

**Comment by fritjof-b** [comment]
LGTM! @exook

**Comment by exook** [comment]
I think we should merge this to main after we've done Dev -> main

**Comment by exook** [comment]
Great job @sekkar! Just like your other contributions: aaa516f, 283ee93, 48e2d8c, 2cadfa0

**Review by exook — APPROVED** [review]
Great work on this @OliverWoolland , @fritjof-b , @sekkar

**Pull request merged**
